language: node_js
node_js:
- stable
notifications:
  slack:
    secure: bgWVbU0WJy0AWclkyR21fO1ejXpNAYNL78ZxNBT3XoabB+7MFbtqc84JNR8sQ1xY2Otsmzms4lUhIsFPZdjZgfTXUmiXnpUT3pHS/WU0nOas+fJbizFK/BkwN34BbCQj5RjLEv44E7wjO+KkdxeI1MsYKAWC8Z0KT+2izVhfojNib2IX/HQtKqFYxGveoqx325HUMRwj9gcRyWnvCQKDxpY/EdQnbXaPvpOSaRM5n9rDB4e2ONxjxPwPyfksOvy9jMzrlSpRGbizAMVldmdaAXrH9FDFVffnwPDMVbVN0P42ZezOsCEHksOvL8fEQV7UsNBS7JT4Oueq3y1PS0+wWO6dlj8NKQ7hf4jTt/SAmbuchLvn3mwlNe9UZm1NXT7nn+RUDnzCHJWmuee0Rs8PJtsKX7eKN0gSoIbzahheypCjEA7vschVLIYL3mIOCe6WQliMZ2jb9VmUf2hE7bAZybtZ3xVewDRJkR39jE3TPA2forqHfQtwQhLPdZoC1xFl6CfaSsdBVImzPHAbvsWO5zdCIPws1MLXyDyL4V/fGm/2vnf3nJexlIaN1fPbEtIpOLY+VyypizDViBf0l9YwS20D4WZ4nW5uYXpSItSui9/PsXFyCgq8Z7JJMSQjhCXgSQ3KBHryTkapzlMAz8ZawAQuXxPsyI5E6N/DRxl9uw8=
